# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/Users/chetan/Continuum/Continuum/packages/shared/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'darwin-arm64': '/Users/chetan/.npm/_npx/cc9dcd50cd5d7787/node_modules/prisma/query-engine-darwin-arm64'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    document: 'actions.DocumentActions[models.Document]'
    embedding: 'actions.EmbeddingActions[models.Embedding]'
    driftwindow: 'actions.DriftWindowActions[models.DriftWindow]'
    modelversion: 'actions.ModelVersionActions[models.ModelVersion]'
    trainingjob: 'actions.TrainingJobActions[models.TrainingJob]'

    __slots__ = (
        'document',
        'embedding',
        'driftwindow',
        'modelversion',
        'trainingjob',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set(['postgresqlExtensions']),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.document = actions.DocumentActions[models.Document](self, models.Document)
        self.embedding = actions.EmbeddingActions[models.Embedding](self, models.Embedding)
        self.driftwindow = actions.DriftWindowActions[models.DriftWindow](self, models.DriftWindow)
        self.modelversion = actions.ModelVersionActions[models.ModelVersion](self, models.ModelVersion)
        self.trainingjob = actions.TrainingJobActions[models.TrainingJob](self, models.TrainingJob)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/Users/chetan/Continuum/Continuum/packages/shared/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    document: 'DocumentBatchActions'
    embedding: 'EmbeddingBatchActions'
    driftwindow: 'DriftWindowBatchActions'
    modelversion: 'ModelVersionBatchActions'
    trainingjob: 'TrainingJobBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.document = DocumentBatchActions(self)
        self.embedding = EmbeddingBatchActions(self)
        self.driftwindow = DriftWindowBatchActions(self)
        self.modelversion = ModelVersionBatchActions(self)
        self.trainingjob = TrainingJobBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class DocumentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.DocumentCreateInput,
        include: Optional[types.DocumentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Document,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.DocumentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Document,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.DocumentWhereUniqueInput,
        include: Optional[types.DocumentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Document,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.DocumentUpdateInput,
        where: types.DocumentWhereUniqueInput,
        include: Optional[types.DocumentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Document,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.DocumentWhereUniqueInput,
        data: types.DocumentUpsertInput,
        include: Optional[types.DocumentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Document,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.DocumentUpdateManyMutationInput,
        where: types.DocumentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Document,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.DocumentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Document,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class EmbeddingBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.EmbeddingCreateInput,
        include: Optional[types.EmbeddingInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Embedding,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.EmbeddingCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Embedding,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.EmbeddingWhereUniqueInput,
        include: Optional[types.EmbeddingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Embedding,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.EmbeddingUpdateInput,
        where: types.EmbeddingWhereUniqueInput,
        include: Optional[types.EmbeddingInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Embedding,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.EmbeddingWhereUniqueInput,
        data: types.EmbeddingUpsertInput,
        include: Optional[types.EmbeddingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Embedding,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.EmbeddingUpdateManyMutationInput,
        where: types.EmbeddingWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Embedding,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.EmbeddingWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Embedding,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class DriftWindowBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.DriftWindowCreateInput,
        include: Optional[types.DriftWindowInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.DriftWindow,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.DriftWindowCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.DriftWindow,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.DriftWindowWhereUniqueInput,
        include: Optional[types.DriftWindowInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.DriftWindow,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.DriftWindowUpdateInput,
        where: types.DriftWindowWhereUniqueInput,
        include: Optional[types.DriftWindowInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.DriftWindow,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.DriftWindowWhereUniqueInput,
        data: types.DriftWindowUpsertInput,
        include: Optional[types.DriftWindowInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.DriftWindow,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.DriftWindowUpdateManyMutationInput,
        where: types.DriftWindowWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.DriftWindow,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.DriftWindowWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.DriftWindow,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ModelVersionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ModelVersionCreateInput,
        include: Optional[types.ModelVersionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ModelVersion,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ModelVersionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ModelVersion,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ModelVersionWhereUniqueInput,
        include: Optional[types.ModelVersionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ModelVersion,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ModelVersionUpdateInput,
        where: types.ModelVersionWhereUniqueInput,
        include: Optional[types.ModelVersionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ModelVersion,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ModelVersionWhereUniqueInput,
        data: types.ModelVersionUpsertInput,
        include: Optional[types.ModelVersionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ModelVersion,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ModelVersionUpdateManyMutationInput,
        where: types.ModelVersionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ModelVersion,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ModelVersionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ModelVersion,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TrainingJobBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TrainingJobCreateInput,
        include: Optional[types.TrainingJobInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.TrainingJob,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TrainingJobCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.TrainingJob,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TrainingJobWhereUniqueInput,
        include: Optional[types.TrainingJobInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.TrainingJob,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TrainingJobUpdateInput,
        where: types.TrainingJobWhereUniqueInput,
        include: Optional[types.TrainingJobInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.TrainingJob,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TrainingJobWhereUniqueInput,
        data: types.TrainingJobUpsertInput,
        include: Optional[types.TrainingJobInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.TrainingJob,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TrainingJobUpdateManyMutationInput,
        where: types.TrainingJobWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.TrainingJob,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TrainingJobWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.TrainingJob,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma