# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class DriftWindowSize(StrEnum):
    FIVE_MIN = 'FIVE_MIN'
    ONE_HOUR = 'ONE_HOUR'
    TWENTY_FOUR_HOUR = 'TWENTY_FOUR_HOUR'

class ModelStatus(StrEnum):
    DRAFT = 'DRAFT'
    EVALUATING = 'EVALUATING'
    PENDING_EVAL = 'PENDING_EVAL'
    PASSED = 'PASSED'
    REJECTED = 'REJECTED'
    ACTIVE = 'ACTIVE'
    ARCHIVED = 'ARCHIVED'

class TrainingJobStatus(StrEnum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

class TrainingTrigger(StrEnum):
    DRIFT_ALERT = 'DRIFT_ALERT'
    MANUAL = 'MANUAL'
    SCHEDULED = 'SCHEDULED'

