from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Document',
    'Embedding',
    'DriftWindow',
    'ModelVersion',
    'TrainingJob',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Document': {
        'embedding': 'Embedding',
    },
    'Embedding': {
        'document': 'Document',
        'modelVersion': 'ModelVersion',
    },
    'DriftWindow': {
        'baseline': 'DriftWindow',
        'derived': 'DriftWindow',
        'trainingJobs': 'TrainingJob',
    },
    'ModelVersion': {
        'trainingJob': 'TrainingJob',
        'embeddings': 'Embedding',
    },
    'TrainingJob': {
        'driftWindow': 'DriftWindow',
        'modelVersion': 'ModelVersion',
    },
}

# fmt: on