# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
import os
import logging
import inspect
import warnings
from collections import OrderedDict

from pydantic import BaseModel, Field

from . import types, enums, errors, fields, bases
from ._types import FuncType
from ._compat import model_rebuild, field_validator
from ._builder import serialize_base64
from .generator import partial_models_ctx, PartialModelField


log: logging.Logger = logging.getLogger(__name__)
_created_partial_types: Set[str] = set()

class Document(bases.BaseDocument):
    """A document submitted by a client system, before embedding.
    """

    id: _str
    externalId: _str
    """Caller-supplied natural key. Stable across re-ingestion of the same document.
    """

    idempotencyKey: _str
    """Deduplication key for exactly-once consumption. Unique across the whole stream.
    """

    text: _str
    source: _str
    """Originating system, e.g. "support-tickets" or "product-catalog".
    """

    occurredAt: datetime.datetime
    """Event time as reported by the producer, not ingestion time.
    """

    metadata: Optional['fields.Json'] = None
    contentHash: _str
    """SHA-256 of `text`, hex encoded. Used for corpus dedup and eval reproducibility.
    """

    objectKey: Optional[_str] = None
    """MinIO object key holding the raw ingested payload. Null until the upload lands.
    """

    ingestedAt: datetime.datetime
    embedding: Optional['models.Embedding'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.DocumentKeys']] = None,
        exclude: Optional[Iterable['types.DocumentKeys']] = None,
        required: Optional[Iterable['types.DocumentKeys']] = None,
        optional: Optional[Iterable['types.DocumentKeys']] = None,
        relations: Optional[Mapping['types.DocumentRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.DocumentKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _Document_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _Document_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _Document_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _Document_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _Document_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _Document_relational_fields:
                        raise errors.UnknownRelationalFieldError('Document', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid Document / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'Document',
            }
        )
        _created_partial_types.add(name)


class Embedding(bases.BaseEmbedding):
    """The 384-dimensional embedding of a document, produced by a specific model version.
    """

    id: _str
    documentId: _str
    document: Optional['models.Document'] = None
    modelVersionId: Optional[_str] = None
    """Null only for embeddings produced by the un-tuned base model before any
    version was registered.
    """

    modelVersion: Optional['models.ModelVersion'] = None
    dimension: _int
    """Denormalised for cheap validation; must equal 384 for the MiniLM family.
    """

    createdAt: datetime.datetime

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.EmbeddingKeys']] = None,
        exclude: Optional[Iterable['types.EmbeddingKeys']] = None,
        required: Optional[Iterable['types.EmbeddingKeys']] = None,
        optional: Optional[Iterable['types.EmbeddingKeys']] = None,
        relations: Optional[Mapping['types.EmbeddingRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.EmbeddingKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _Embedding_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _Embedding_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _Embedding_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _Embedding_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _Embedding_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _Embedding_relational_fields:
                        raise errors.UnknownRelationalFieldError('Embedding', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid Embedding / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'Embedding',
            }
        )
        _created_partial_types.add(name)


class DriftWindow(bases.BaseDriftWindow):
    """An aggregated drift measurement over one time window.
    """

    id: _str
    windowSize: 'enums.DriftWindowSize'
    windowStart: datetime.datetime
    windowEnd: datetime.datetime
    documentCount: _int
    klDivergence: Optional[_float] = None
    """Divergence measures against `baseline`. Null until enough samples accumulate.
    """

    wassersteinDistance: Optional[_float] = None
    driftScore: _float
    """Normalised composite score in [0, 1].
    """

    threshold: _float
    """Threshold in force when this window was scored, captured for auditability.
    """

    breached: _bool
    baselineId: Optional[_str] = None
    """The window this one was compared against. Null for baseline windows themselves.
    """

    baseline: Optional['models.DriftWindow'] = None
    derived: Optional[List['models.DriftWindow']] = None
    trainingJobs: Optional[List['models.TrainingJob']] = None
    createdAt: datetime.datetime

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.DriftWindowKeys']] = None,
        exclude: Optional[Iterable['types.DriftWindowKeys']] = None,
        required: Optional[Iterable['types.DriftWindowKeys']] = None,
        optional: Optional[Iterable['types.DriftWindowKeys']] = None,
        relations: Optional[Mapping['types.DriftWindowRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.DriftWindowKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _DriftWindow_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _DriftWindow_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _DriftWindow_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _DriftWindow_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _DriftWindow_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _DriftWindow_relational_fields:
                        raise errors.UnknownRelationalFieldError('DriftWindow', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid DriftWindow / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'DriftWindow',
            }
        )
        _created_partial_types.add(name)


class ModelVersion(bases.BaseModelVersion):
    """An entry in the model registry.
    """

    id: _str
    version: _str
    """Human-facing identifier, e.g. "2026.07.26-1". Immutable once created.
    """

    baseModel: _str
    """Hugging Face id of the model this version was adapted from.
    """

    status: 'enums.ModelStatus'
    artifactUri: Optional[_str] = None
    """MinIO URI of the exported ONNX artifact.
    """

    artifactSha256: Optional[_str] = None
    """SHA-256 of the artifact, hex encoded. Verified on load before serving.
    """

    artifactBytes: Optional[_int] = None
    embeddingDim: _int
    loraRank: Optional[_int] = None
    """LoRA rank used for this adapter. Null for the base model.
    """

    metrics: Optional['fields.Json'] = None
    """Eval results for this version, e.g. { "mrr": 0.71, "recall_at_5": 0.83 }.
    """

    baselineMetrics: Optional['fields.Json'] = None
    """The same metric shape for the version this one was gated against.
    """

    improvementPct: Optional[_float] = None
    """Relative MRR improvement over baseline, as a fraction. Gate requires > 0.10.
    """

    activatedAt: Optional[datetime.datetime] = None
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    trainingJob: Optional['models.TrainingJob'] = None
    embeddings: Optional[List['models.Embedding']] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.ModelVersionKeys']] = None,
        exclude: Optional[Iterable['types.ModelVersionKeys']] = None,
        required: Optional[Iterable['types.ModelVersionKeys']] = None,
        optional: Optional[Iterable['types.ModelVersionKeys']] = None,
        relations: Optional[Mapping['types.ModelVersionRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.ModelVersionKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _ModelVersion_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _ModelVersion_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _ModelVersion_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _ModelVersion_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _ModelVersion_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _ModelVersion_relational_fields:
                        raise errors.UnknownRelationalFieldError('ModelVersion', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid ModelVersion / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'ModelVersion',
            }
        )
        _created_partial_types.add(name)


class TrainingJob(bases.BaseTrainingJob):
    """An asynchronous LoRA fine-tuning run.
    """

    id: _str
    status: 'enums.TrainingJobStatus'
    trigger: 'enums.TrainingTrigger'
    driftWindowId: Optional[_str] = None
    """The drift window that triggered this job. Null for MANUAL and SCHEDULED runs.
    """

    driftWindow: Optional['models.DriftWindow'] = None
    modelVersionId: Optional[_str] = None
    """The version this job produced. Null until training succeeds.
    """

    modelVersion: Optional['models.ModelVersion'] = None
    baseModel: _str
    hyperparameters: 'fields.Json'
    """Full hyperparameter set, captured so a run can be reproduced exactly.
    """

    sampleCount: Optional[_int] = None
    """Number of documents sampled into the training set.
    """

    attempts: _int
    maxAttempts: _int
    error: Optional[_str] = None
    """Failure message from the final attempt. Null unless status is FAILED.
    """

    lossHistory: Optional['fields.Json'] = None
    """Per-step loss, streamed to the dashboard: [{ "step": 1, "loss": 0.42 }, ...].
    """

    queuedAt: datetime.datetime
    startedAt: Optional[datetime.datetime] = None
    finishedAt: Optional[datetime.datetime] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.TrainingJobKeys']] = None,
        exclude: Optional[Iterable['types.TrainingJobKeys']] = None,
        required: Optional[Iterable['types.TrainingJobKeys']] = None,
        optional: Optional[Iterable['types.TrainingJobKeys']] = None,
        relations: Optional[Mapping['types.TrainingJobRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.TrainingJobKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _TrainingJob_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _TrainingJob_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _TrainingJob_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _TrainingJob_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _TrainingJob_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _TrainingJob_relational_fields:
                        raise errors.UnknownRelationalFieldError('TrainingJob', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid TrainingJob / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'TrainingJob',
            }
        )
        _created_partial_types.add(name)



_Document_relational_fields: Set[str] = {
        'embedding',
    }
_Document_fields: Dict['types.DocumentKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('externalId', {
            'name': 'externalId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Caller-supplied natural key. Stable across re-ingestion of the same document.''',
        }),
        ('idempotencyKey', {
            'name': 'idempotencyKey',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Deduplication key for exactly-once consumption. Unique across the whole stream.''',
        }),
        ('text', {
            'name': 'text',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('source', {
            'name': 'source',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Originating system, e.g. "support-tickets" or "product-catalog".''',
        }),
        ('occurredAt', {
            'name': 'occurredAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': '''Event time as reported by the producer, not ingestion time.''',
        }),
        ('metadata', {
            'name': 'metadata',
            'is_list': False,
            'optional': True,
            'type': 'fields.Json',
            'is_relational': False,
            'documentation': None,
        }),
        ('contentHash', {
            'name': 'contentHash',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': '''SHA-256 of `text`, hex encoded. Used for corpus dedup and eval reproducibility.''',
        }),
        ('objectKey', {
            'name': 'objectKey',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''MinIO object key holding the raw ingested payload. Null until the upload lands.''',
        }),
        ('ingestedAt', {
            'name': 'ingestedAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('embedding', {
            'name': 'embedding',
            'is_list': False,
            'optional': True,
            'type': 'models.Embedding',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_Embedding_relational_fields: Set[str] = {
        'document',
        'modelVersion',
    }
_Embedding_fields: Dict['types.EmbeddingKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('documentId', {
            'name': 'documentId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('document', {
            'name': 'document',
            'is_list': False,
            'optional': True,
            'type': 'models.Document',
            'is_relational': True,
            'documentation': None,
        }),
        ('modelVersionId', {
            'name': 'modelVersionId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Null only for embeddings produced by the un-tuned base model before any
version was registered.''',
        }),
        ('modelVersion', {
            'name': 'modelVersion',
            'is_list': False,
            'optional': True,
            'type': 'models.ModelVersion',
            'is_relational': True,
            'documentation': None,
        }),
        ('dimension', {
            'name': 'dimension',
            'is_list': False,
            'optional': False,
            'type': '_int',
            'is_relational': False,
            'documentation': '''Denormalised for cheap validation; must equal 384 for the MiniLM family.''',
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
    ],
)

_DriftWindow_relational_fields: Set[str] = {
        'baseline',
        'derived',
        'trainingJobs',
    }
_DriftWindow_fields: Dict['types.DriftWindowKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('windowSize', {
            'name': 'windowSize',
            'is_list': False,
            'optional': False,
            'type': 'enums.DriftWindowSize',
            'is_relational': False,
            'documentation': None,
        }),
        ('windowStart', {
            'name': 'windowStart',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('windowEnd', {
            'name': 'windowEnd',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('documentCount', {
            'name': 'documentCount',
            'is_list': False,
            'optional': False,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('klDivergence', {
            'name': 'klDivergence',
            'is_list': False,
            'optional': True,
            'type': '_float',
            'is_relational': False,
            'documentation': '''Divergence measures against `baseline`. Null until enough samples accumulate.''',
        }),
        ('wassersteinDistance', {
            'name': 'wassersteinDistance',
            'is_list': False,
            'optional': True,
            'type': '_float',
            'is_relational': False,
            'documentation': None,
        }),
        ('driftScore', {
            'name': 'driftScore',
            'is_list': False,
            'optional': False,
            'type': '_float',
            'is_relational': False,
            'documentation': '''Normalised composite score in [0, 1].''',
        }),
        ('threshold', {
            'name': 'threshold',
            'is_list': False,
            'optional': False,
            'type': '_float',
            'is_relational': False,
            'documentation': '''Threshold in force when this window was scored, captured for auditability.''',
        }),
        ('breached', {
            'name': 'breached',
            'is_list': False,
            'optional': False,
            'type': '_bool',
            'is_relational': False,
            'documentation': None,
        }),
        ('baselineId', {
            'name': 'baselineId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''The window this one was compared against. Null for baseline windows themselves.''',
        }),
        ('baseline', {
            'name': 'baseline',
            'is_list': False,
            'optional': True,
            'type': 'models.DriftWindow',
            'is_relational': True,
            'documentation': None,
        }),
        ('derived', {
            'name': 'derived',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.DriftWindow\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('trainingJobs', {
            'name': 'trainingJobs',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.TrainingJob\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
    ],
)

_ModelVersion_relational_fields: Set[str] = {
        'trainingJob',
        'embeddings',
    }
_ModelVersion_fields: Dict['types.ModelVersionKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('version', {
            'name': 'version',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Human-facing identifier, e.g. "2026.07.26-1". Immutable once created.''',
        }),
        ('baseModel', {
            'name': 'baseModel',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Hugging Face id of the model this version was adapted from.''',
        }),
        ('status', {
            'name': 'status',
            'is_list': False,
            'optional': False,
            'type': 'enums.ModelStatus',
            'is_relational': False,
            'documentation': None,
        }),
        ('artifactUri', {
            'name': 'artifactUri',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''MinIO URI of the exported ONNX artifact.''',
        }),
        ('artifactSha256', {
            'name': 'artifactSha256',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''SHA-256 of the artifact, hex encoded. Verified on load before serving.''',
        }),
        ('artifactBytes', {
            'name': 'artifactBytes',
            'is_list': False,
            'optional': True,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('embeddingDim', {
            'name': 'embeddingDim',
            'is_list': False,
            'optional': False,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('loraRank', {
            'name': 'loraRank',
            'is_list': False,
            'optional': True,
            'type': '_int',
            'is_relational': False,
            'documentation': '''LoRA rank used for this adapter. Null for the base model.''',
        }),
        ('metrics', {
            'name': 'metrics',
            'is_list': False,
            'optional': True,
            'type': 'fields.Json',
            'is_relational': False,
            'documentation': '''Eval results for this version, e.g. { "mrr": 0.71, "recall_at_5": 0.83 }.''',
        }),
        ('baselineMetrics', {
            'name': 'baselineMetrics',
            'is_list': False,
            'optional': True,
            'type': 'fields.Json',
            'is_relational': False,
            'documentation': '''The same metric shape for the version this one was gated against.''',
        }),
        ('improvementPct', {
            'name': 'improvementPct',
            'is_list': False,
            'optional': True,
            'type': '_float',
            'is_relational': False,
            'documentation': '''Relative MRR improvement over baseline, as a fraction. Gate requires > 0.10.''',
        }),
        ('activatedAt', {
            'name': 'activatedAt',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('updatedAt', {
            'name': 'updatedAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('trainingJob', {
            'name': 'trainingJob',
            'is_list': False,
            'optional': True,
            'type': 'models.TrainingJob',
            'is_relational': True,
            'documentation': None,
        }),
        ('embeddings', {
            'name': 'embeddings',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.Embedding\']',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_TrainingJob_relational_fields: Set[str] = {
        'driftWindow',
        'modelVersion',
    }
_TrainingJob_fields: Dict['types.TrainingJobKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('status', {
            'name': 'status',
            'is_list': False,
            'optional': False,
            'type': 'enums.TrainingJobStatus',
            'is_relational': False,
            'documentation': None,
        }),
        ('trigger', {
            'name': 'trigger',
            'is_list': False,
            'optional': False,
            'type': 'enums.TrainingTrigger',
            'is_relational': False,
            'documentation': None,
        }),
        ('driftWindowId', {
            'name': 'driftWindowId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''The drift window that triggered this job. Null for MANUAL and SCHEDULED runs.''',
        }),
        ('driftWindow', {
            'name': 'driftWindow',
            'is_list': False,
            'optional': True,
            'type': 'models.DriftWindow',
            'is_relational': True,
            'documentation': None,
        }),
        ('modelVersionId', {
            'name': 'modelVersionId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''The version this job produced. Null until training succeeds.''',
        }),
        ('modelVersion', {
            'name': 'modelVersion',
            'is_list': False,
            'optional': True,
            'type': 'models.ModelVersion',
            'is_relational': True,
            'documentation': None,
        }),
        ('baseModel', {
            'name': 'baseModel',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('hyperparameters', {
            'name': 'hyperparameters',
            'is_list': False,
            'optional': False,
            'type': 'fields.Json',
            'is_relational': False,
            'documentation': '''Full hyperparameter set, captured so a run can be reproduced exactly.''',
        }),
        ('sampleCount', {
            'name': 'sampleCount',
            'is_list': False,
            'optional': True,
            'type': '_int',
            'is_relational': False,
            'documentation': '''Number of documents sampled into the training set.''',
        }),
        ('attempts', {
            'name': 'attempts',
            'is_list': False,
            'optional': False,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('maxAttempts', {
            'name': 'maxAttempts',
            'is_list': False,
            'optional': False,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('error', {
            'name': 'error',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': '''Failure message from the final attempt. Null unless status is FAILED.''',
        }),
        ('lossHistory', {
            'name': 'lossHistory',
            'is_list': False,
            'optional': True,
            'type': 'fields.Json',
            'is_relational': False,
            'documentation': '''Per-step loss, streamed to the dashboard: [{ "step": 1, "loss": 0.42 }, ...].''',
        }),
        ('queuedAt', {
            'name': 'queuedAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('startedAt', {
            'name': 'startedAt',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('finishedAt', {
            'name': 'finishedAt',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
    ],
)



# we have to import ourselves as relation types are namespaced to models
# e.g. models.Post
from . import models, actions

# required to support relationships between models
model_rebuild(Document)
model_rebuild(Embedding)
model_rebuild(DriftWindow)
model_rebuild(ModelVersion)
model_rebuild(TrainingJob)
