-- Continuum initial schema.
--
-- The DDL below the "Prisma-managed" banner is generated by
--   prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
-- and must stay byte-identical to that output so future diffs stay clean.
--
-- The "Hand-authored" section holds constraints and indexes Prisma's schema language
-- cannot express. They are intentional and must be carried forward by hand: regenerating
-- migrations non-interactively would drop them silently. See the header comment in
-- prisma/schema.prisma.

-- ===========================================================================
-- Prisma-managed
-- ===========================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "vector";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- CreateEnum
CREATE TYPE "DriftWindowSize" AS ENUM ('FIVE_MIN', 'ONE_HOUR', 'TWENTY_FOUR_HOUR');

-- CreateEnum
CREATE TYPE "ModelStatus" AS ENUM ('DRAFT', 'EVALUATING', 'PENDING_EVAL', 'PASSED', 'REJECTED', 'ACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "TrainingJobStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "TrainingTrigger" AS ENUM ('DRIFT_ALERT', 'MANUAL', 'SCHEDULED');

-- CreateTable
CREATE TABLE "documents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "external_id" VARCHAR(256) NOT NULL,
    "idempotency_key" VARCHAR(256) NOT NULL,
    "text" TEXT NOT NULL,
    "source" VARCHAR(128) NOT NULL,
    "occurred_at" TIMESTAMPTZ(6) NOT NULL,
    "metadata" JSONB,
    "content_hash" CHAR(64) NOT NULL,
    "object_key" VARCHAR(512),
    "ingested_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "embeddings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "document_id" UUID NOT NULL,
    "model_version_id" UUID,
    "vector" vector(384) NOT NULL,
    "dimension" INTEGER NOT NULL DEFAULT 384,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "embeddings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "drift_windows" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "window_size" "DriftWindowSize" NOT NULL,
    "window_start" TIMESTAMPTZ(6) NOT NULL,
    "window_end" TIMESTAMPTZ(6) NOT NULL,
    "document_count" INTEGER NOT NULL,
    "centroid" vector(384),
    "kl_divergence" DOUBLE PRECISION,
    "wasserstein_distance" DOUBLE PRECISION,
    "drift_score" DOUBLE PRECISION NOT NULL,
    "threshold" DOUBLE PRECISION NOT NULL DEFAULT 0.75,
    "breached" BOOLEAN NOT NULL DEFAULT false,
    "baseline_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "drift_windows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "linguistic_windows" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "window_start" TIMESTAMPTZ(6) NOT NULL,
    "window_end" TIMESTAMPTZ(6) NOT NULL,
    "document_count" INTEGER NOT NULL,
    "entity_kl_divergence" DOUBLE PRECISION NOT NULL,
    "topic_wasserstein" DOUBLE PRECISION NOT NULL,
    "vocab_chi2_pvalue" DOUBLE PRECISION NOT NULL,
    "composite_score" DOUBLE PRECISION NOT NULL,
    "threshold" DOUBLE PRECISION NOT NULL DEFAULT 0.65,
    "breached" BOOLEAN NOT NULL DEFAULT false,
    "new_entities" JSONB NOT NULL,
    "emerging_topics" JSONB NOT NULL,
    "emerging_terms" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "linguistic_windows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "model_versions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "version" VARCHAR(64) NOT NULL,
    "base_model" VARCHAR(256) NOT NULL,
    "status" "ModelStatus" NOT NULL DEFAULT 'DRAFT',
    "artifact_uri" VARCHAR(512),
    "artifact_sha256" CHAR(64),
    "artifact_bytes" BIGINT,
    "domain_tag" VARCHAR(128),
    "onnx_path" VARCHAR(512),
    "embedding_dim" INTEGER NOT NULL DEFAULT 384,
    "lora_rank" INTEGER,
    "metrics" JSONB,
    "baseline_metrics" JSONB,
    "improvement_pct" DOUBLE PRECISION,
    "eval_mrr" DOUBLE PRECISION,
    "activated_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "model_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_jobs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "status" "TrainingJobStatus" NOT NULL DEFAULT 'QUEUED',
    "trigger" "TrainingTrigger" NOT NULL,
    "drift_window_id" UUID,
    "model_version_id" UUID,
    "base_model" VARCHAR(256) NOT NULL,
    "hyperparameters" JSONB NOT NULL,
    "sample_count" INTEGER,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 3,
    "error" TEXT,
    "loss_history" JSONB,
    "queued_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ(6),
    "finished_at" TIMESTAMPTZ(6),

    CONSTRAINT "training_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_linguistic_signals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "training_job_id" UUID NOT NULL,
    "linguistic_window_id" UUID NOT NULL,
    "drift_window_id" UUID,
    "signal_weight" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "training_linguistic_signals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "documents_occurred_at_idx" ON "documents"("occurred_at");

-- CreateIndex
CREATE INDEX "documents_source_occurred_at_idx" ON "documents"("source", "occurred_at");

-- CreateIndex
CREATE INDEX "documents_content_hash_idx" ON "documents"("content_hash");

-- CreateIndex
CREATE UNIQUE INDEX "documents_idempotency_key_key" ON "documents"("idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "documents_source_external_id_key" ON "documents"("source", "external_id");

-- CreateIndex
CREATE UNIQUE INDEX "embeddings_document_id_key" ON "embeddings"("document_id");

-- CreateIndex
CREATE INDEX "embeddings_model_version_id_idx" ON "embeddings"("model_version_id");

-- CreateIndex
CREATE INDEX "embeddings_created_at_idx" ON "embeddings"("created_at");

-- CreateIndex
CREATE INDEX "drift_windows_breached_window_start_idx" ON "drift_windows"("breached", "window_start");

-- CreateIndex
CREATE INDEX "drift_windows_window_start_idx" ON "drift_windows"("window_start");

-- CreateIndex
CREATE UNIQUE INDEX "drift_windows_window_size_window_start_key" ON "drift_windows"("window_size", "window_start");

-- CreateIndex
CREATE INDEX "linguistic_windows_breached_window_start_idx" ON "linguistic_windows"("breached", "window_start");

-- CreateIndex
CREATE INDEX "linguistic_windows_window_start_idx" ON "linguistic_windows"("window_start");

-- CreateIndex
CREATE UNIQUE INDEX "linguistic_windows_window_start_window_end_key" ON "linguistic_windows"("window_start", "window_end");

-- CreateIndex
CREATE UNIQUE INDEX "model_versions_version_key" ON "model_versions"("version");

-- CreateIndex
CREATE INDEX "model_versions_status_idx" ON "model_versions"("status");

-- CreateIndex
CREATE INDEX "model_versions_created_at_idx" ON "model_versions"("created_at");

-- CreateIndex
CREATE UNIQUE INDEX "training_jobs_model_version_id_key" ON "training_jobs"("model_version_id");

-- CreateIndex
CREATE INDEX "training_jobs_status_queued_at_idx" ON "training_jobs"("status", "queued_at");

-- CreateIndex
CREATE INDEX "training_jobs_drift_window_id_idx" ON "training_jobs"("drift_window_id");

-- CreateIndex
CREATE UNIQUE INDEX "training_jobs_trigger_drift_window_id_key" ON "training_jobs"("trigger", "drift_window_id");

-- CreateIndex
CREATE UNIQUE INDEX "training_linguistic_signals_training_job_id_linguistic_window_id_key" ON "training_linguistic_signals"("training_job_id", "linguistic_window_id");

-- CreateIndex
CREATE INDEX "training_linguistic_signals_linguistic_window_id_idx" ON "training_linguistic_signals"("linguistic_window_id");

-- CreateIndex
CREATE INDEX "training_linguistic_signals_drift_window_id_idx" ON "training_linguistic_signals"("drift_window_id");

-- AddForeignKey
ALTER TABLE "embeddings" ADD CONSTRAINT "embeddings_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "embeddings" ADD CONSTRAINT "embeddings_model_version_id_fkey" FOREIGN KEY ("model_version_id") REFERENCES "model_versions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "drift_windows" ADD CONSTRAINT "drift_windows_baseline_id_fkey" FOREIGN KEY ("baseline_id") REFERENCES "drift_windows"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_jobs" ADD CONSTRAINT "training_jobs_drift_window_id_fkey" FOREIGN KEY ("drift_window_id") REFERENCES "drift_windows"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_jobs" ADD CONSTRAINT "training_jobs_model_version_id_fkey" FOREIGN KEY ("model_version_id") REFERENCES "model_versions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_linguistic_signals" ADD CONSTRAINT "training_linguistic_signals_training_job_id_fkey" FOREIGN KEY ("training_job_id") REFERENCES "training_jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_linguistic_signals" ADD CONSTRAINT "training_linguistic_signals_linguistic_window_id_fkey" FOREIGN KEY ("linguistic_window_id") REFERENCES "linguistic_windows"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_linguistic_signals" ADD CONSTRAINT "training_linguistic_signals_drift_window_id_fkey" FOREIGN KEY ("drift_window_id") REFERENCES "drift_windows"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ===========================================================================
-- Hand-authored: not expressible in the Prisma schema language
-- ===========================================================================

-- Approximate nearest-neighbour index for embedding retrieval.
--
-- Cosine distance (`<=>`) is the operator class: sentence-transformers MiniLM outputs are
-- L2-normalised, so cosine and inner product rank identically, and cosine keeps scores in
-- a fixed [0, 2] range that is easier to reason about in drift math.
--
-- m = 16 / ef_construction = 64 are pgvector's defaults. They are stated explicitly so a
-- later tuning change shows up as a deliberate diff rather than a silent default shift.
-- Build time is negligible here because the table is empty; rebuilding after bulk load is
-- the drift engine's responsibility.
CREATE INDEX "embeddings_vector_hnsw_idx"
    ON "embeddings"
    USING hnsw ("vector" vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- At most one model version may serve traffic at a time. A partial unique index makes the
-- invariant a database guarantee rather than an application convention, so a racing
-- activation fails loudly instead of splitting traffic across two models.
CREATE UNIQUE INDEX "model_versions_one_active_idx"
    ON "model_versions" ((status))
    WHERE status = 'ACTIVE';

-- Embedding width is fixed by the model family. A mismatch means a serving/registry skew
-- that must fail at write time, not at query time.
ALTER TABLE "embeddings"
    ADD CONSTRAINT "embeddings_dimension_check" CHECK ("dimension" = 384);

ALTER TABLE "model_versions"
    ADD CONSTRAINT "model_versions_embedding_dim_check" CHECK ("embedding_dim" = 384);

-- Drift scores and thresholds are normalised to [0, 1]; divergences are non-negative by
-- definition. Windows must be non-empty intervals with a non-negative document count.
ALTER TABLE "drift_windows"
    ADD CONSTRAINT "drift_windows_drift_score_check" CHECK ("drift_score" >= 0 AND "drift_score" <= 1),
    ADD CONSTRAINT "drift_windows_threshold_check" CHECK ("threshold" >= 0 AND "threshold" <= 1),
    ADD CONSTRAINT "drift_windows_kl_divergence_check" CHECK ("kl_divergence" IS NULL OR "kl_divergence" >= 0),
    ADD CONSTRAINT "drift_windows_wasserstein_check" CHECK ("wasserstein_distance" IS NULL OR "wasserstein_distance" >= 0),
    ADD CONSTRAINT "drift_windows_interval_check" CHECK ("window_end" > "window_start"),
    ADD CONSTRAINT "drift_windows_document_count_check" CHECK ("document_count" >= 0),
    -- A centroid exists exactly when the window contains at least one document.
    ADD CONSTRAINT "drift_windows_centroid_presence_check"
        CHECK (("document_count" = 0) = ("centroid" IS NULL));

ALTER TABLE "linguistic_windows"
    ADD CONSTRAINT "linguistic_windows_interval_check" CHECK ("window_end" > "window_start"),
    ADD CONSTRAINT "linguistic_windows_document_count_check" CHECK ("document_count" >= 0),
    ADD CONSTRAINT "linguistic_windows_entity_kl_check" CHECK ("entity_kl_divergence" >= 0),
    ADD CONSTRAINT "linguistic_windows_topic_wasserstein_check" CHECK ("topic_wasserstein" >= 0),
    ADD CONSTRAINT "linguistic_windows_vocab_pvalue_check" CHECK ("vocab_chi2_pvalue" >= 0 AND "vocab_chi2_pvalue" <= 1),
    ADD CONSTRAINT "linguistic_windows_composite_score_check" CHECK ("composite_score" >= 0 AND "composite_score" <= 1),
    ADD CONSTRAINT "linguistic_windows_threshold_check" CHECK ("threshold" >= 0 AND "threshold" <= 1);

-- Content and artifact digests are lowercase hex SHA-256. Enforcing the shape here keeps
-- deduplication and artifact-integrity checks from being defeated by casing drift.
ALTER TABLE "documents"
    ADD CONSTRAINT "documents_content_hash_check" CHECK ("content_hash" ~ '^[0-9a-f]{64}$');

ALTER TABLE "model_versions"
    ADD CONSTRAINT "model_versions_artifact_sha256_check"
        CHECK ("artifact_sha256" IS NULL OR "artifact_sha256" ~ '^[0-9a-f]{64}$');

-- Retry accounting must stay coherent: attempts never exceed the configured ceiling, and a
-- ceiling of zero would mean a job that can never run.
ALTER TABLE "training_jobs"
    ADD CONSTRAINT "training_jobs_max_attempts_check" CHECK ("max_attempts" >= 1),
    ADD CONSTRAINT "training_jobs_attempts_check" CHECK ("attempts" >= 0 AND "attempts" <= "max_attempts");

ALTER TABLE "training_linguistic_signals"
    ADD CONSTRAINT "training_linguistic_signals_weight_check" CHECK ("signal_weight" >= 0 AND "signal_weight" <= 1);
