# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embed.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mbed.proto\x12\tcontinuum\"9\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"m\n\x12\x45mbedBatchResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.continuum.Embedding\x12\x1a\n\x12model_version_used\x18\x02 \x01(\t\x12\x11\n\tdimension\x18\x03 \x01(\x05\"\x1b\n\tEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32Y\n\x0c\x45mbedService\x12I\n\nEmbedBatch\x12\x1c.continuum.EmbedBatchRequest\x1a\x1d.continuum.EmbedBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDBATCHREQUEST']._serialized_start=26
  _globals['_EMBEDBATCHREQUEST']._serialized_end=83
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=85
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=194
  _globals['_EMBEDDING']._serialized_start=196
  _globals['_EMBEDDING']._serialized_end=223
  _globals['_EMBEDSERVICE']._serialized_start=225
  _globals['_EMBEDSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
